-d E:\application_project\gowin_project\project_main_5_23\project_main\project_main\impl\gwsynthesis\project_main.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\application_project\gowin_project\project_main_5_23\project_main\project_main\src\project_main.cst
-cfg E:\application_project\gowin_project\project_main_5_23\project_main\project_main\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
